export default {
    STATE_NONE: -1,
    STATE_LOGIN: 0,
    STATE_SIGNUP: 1,
    STATE_DASHBOARD: 2,
    STATE_LOGOUT: 3,
    STATE_INCOME_EXPENSES: 4,
    STATE_CREATE_INCOME: 5,
    STATE_CREATE_EXPENSE: 6,
    STATE_EDIT_INCOME: 7,
    STATE_EDIT_EXPENSE: 8,
    STATE_CREATE_CATEGORY_INCOME: 9,
    STATE_CREATE_CATEGORY_EXPENSE: 10,
    STATE_EDIT_CATEGORY_INCOME: 11,
    STATE_EDIT_CATEGORY_EXPENSE: 12,
    STATE_CATEGORY_INCOME: 13,
    STATE_CATEGORY_EXPENSE: 14,
    ROUTE_LOGIN: "/login",
    ROUTE_SIGNUP: "/signup",
    ROUTE_DASHBOARD: "/",
    ROUTE_LOGOUT: "/logout",
    ROUTE_INCOME_EXPENSES: "/common",
    ROUTE_CREATE_INCOME: "/create/income",
    ROUTE_CREATE_EXPENSE: "/create/expense",
    ROUTE_EDIT_INCOME: "/edit/income",
    ROUTE_EDIT_EXPENSE: "/edit/expense",
    ROUTE_CATEGORY_INCOME: "/category/income",
    ROUTE_CATEGORY_EXPENSE: "/category/expense",
    ROUTE_CREATE_CATEGORY_INCOME: "/create/category/income",
    ROUTE_CREATE_CATEGORY_EXPENSE: "/create/category/expense",
    ROUTE_EDIT_CATEGORY_INCOME: "/edit/category/income",
    ROUTE_EDIT_CATEGORY_EXPENSE: "/edit/category/expense",
    ROUTE_DELETE_CATEGORY_INCOME: "/delete/category/income",
    ROUTE_DELETE_CATEGORY_EXPENSE: "/delete/category/expense",
    ROUTE_DELETE_OPERATION: "/delete/operation",
    DASHBOARD_HOME: "Главная",
    DASHBOARD_INCOME_EXPENSES: "Доходы & расходы",
    DASHBOARD_CREATE_NEW: "Создание дохода/расхода",
    DASHBOARD_EDIT_NEW: "Редактирование дохода/расхода",
    DASHBOARD_CATEGORY_INCOME: "Доходы",
    DASHBOARD_CATEGORY_EXPENSE: "Расходы",
    DASHBOARD_CREATE_CATEGORY_NEW: "Создание категории",
    DASHBOARD_EDIT_CATEGORY: "Редактирование категории",
}